frequency: 30
sensor_timeout: 0.1

two_d_mode: true

odom_frame: odom
base_link_frame: base_link
world_frame: map

odom0: /odometry/filtered
odom0_config: [true, true, true, false, false, false, false, false, false, false, false, false, false, false, false]
odom0_differential: false
odom0_relative: false

imu0: /imu/data
imu0_config: [false, false, false, true, true, false, false, false, false, true, true, false, false, false, false]
imu0_differential: false
imu0_relative: false
imu0_remove_gravitational_acceleration: true
